services:
    talking-skull-devcontainer:
        network_mode: host
        image: talking-skull-devcontainer
        container_name: talking-skull-devcontainer
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
            args:
                - PYTHON_VERSION
                - DEVCONTAINER_USER
        volumes:
            - ..:/workspace:cached
        # This keeps the devcontainer running.
        entrypoint: ["tail", "-f", "/dev/null"]
